version: '3'
services:     
  app:
    image: myapp
    build: ./app
    ports:
      - '3001:3001'
    volumes: 
      - ./app:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: database
    build: ./db
    environment:
      MYSQL_USER: 'mysql'
      MYSQL_DATABASE: 'useradmin'
      MYSQL_PASSWORD: 'Irinka_2000'
      MYSQL_ROOT_PASSWORD: 'Irinka_2000'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'Irinka_2000'
      MYSQL_RANDOM_ROOT_PASSWORD: 'Irinka_2000'
    restart: always
    ports: 
      - '3308:3308'

volumes:
    db-config:
    db-data: